version: "3.5"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: padzd.mssql
    environment:
      # User: SA
      SA_PASSWORD: "Abc12345678"
      ACCEPT_EULA: "Y"
    volumes:
      - c:/data/mssql/data:/var/opt/mssql/data
    ports:
      - 1433:1433